"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { ApiRequestError } from "../lib/api";
import { validateFindingReviewReason } from "../lib/finding-review-model";
import { decideFindingReview, getFindingResolution, getFindingReview, reportManualRemediation, requestFindingReview } from "../lib/remediation-api";
import type { FindingResolution, FindingReview, FindingReviewDecision, FindingReviewRequestType } from "../lib/remediation-contract";
import { newIntentKey, resolutionPresentation, reviewPresentation } from "../lib/remediation-presentation";
import { ConfirmationDialog } from "./confirmation-dialog";
import { StatusBadge } from "./status-badge";

type Command = { kind: "request"; value: FindingReviewRequestType } | { kind: "decision"; value: FindingReviewDecision } | { kind: "report" };
export function FindingGovernancePanel({ auditId, findingId, relatedExecution }: { auditId: string; findingId: string; relatedExecution?: (id: string) => void }) {
  const [resolution, setResolution] = useState<FindingResolution>(); const [review, setReview] = useState<FindingReview>();
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [note, setNote] = useState(""); const [pending, setPending] = useState<Command>(); const key = useRef<string | undefined>(undefined); const commandInFlight = useRef(false);
  const load = useCallback(async (signal?: AbortSignal) => { setLoading(true); setError(""); try { const [nextResolution, nextReview] = await Promise.all([getFindingResolution(auditId, findingId, signal), getFindingReview(auditId, findingId, signal)]); setResolution(nextResolution); setReview(nextReview); if (nextResolution.fixExecutionId) relatedExecution?.(nextResolution.fixExecutionId); } catch (value) { if ((value as { name?: string })?.name !== "AbortError") setError(safeGovernanceError(value)); } finally { if (!signal?.aborted) setLoading(false); } }, [auditId, findingId, relatedExecution]);
  useEffect(() => { const controller = new AbortController(); void load(controller.signal); return () => controller.abort(); }, [load]);
  function prepare(command: Command) { const reasonRequired = command.kind === "request" && ["ManualRemediation", "Ignore"].includes(command.value) || command.kind === "decision" && command.value === "Ignore"; const validation = reasonRequired ? validateFindingReviewReason(note) : null; if (validation) { setError(validation); return; } if (note.length > 1000 || busy) return; key.current = newIntentKey(); setPending(command); }
  async function submit() { if (!pending || !review || !key.current || commandInFlight.current) return; commandInFlight.current = true; setBusy(true); setError(""); try { let result: FindingReview; if (pending.kind === "request") result = await requestFindingReview(auditId, findingId, pending.value, note, key.current); else if (pending.kind === "decision") { if (!review.reviewCaseId) throw new Error(); result = await decideFindingReview(review.reviewCaseId, pending.value, note, key.current); } else { if (!review.reviewCaseId) throw new Error(); result = await reportManualRemediation(review.reviewCaseId, note, key.current); } setReview(result); setNote(""); setPending(undefined); key.current = undefined; await load(); } catch (value) { if (value instanceof ApiRequestError && value.status === 409) { setPending(undefined); key.current = undefined; await load(); } setError(safeGovernanceError(value)); } finally { commandInFlight.current = false; setBusy(false); } }
  if (loading) return <section className="panel" aria-live="polite" aria-busy="true"><h2>Resolution dan review</h2><p>Memuat state canonical…</p></section>;
  if (!resolution || !review) return <section className="panel error-state" role="alert"><h2>State finding tidak dapat dimuat</h2><p>{error || "Respons tidak tersedia."}</p><button className="button secondary" onClick={() => void load()}>Coba lagi GET</button></section>;
  const resolutionView = resolutionPresentation(resolution.currentState), reviewView = reviewPresentation(review.reviewState);
  return <section className="panel governance-panel" aria-labelledby="governance-title"><div className="section-heading"><div><h2 id="governance-title">Resolution dan review</h2><p>Dua dimensi independen dari snapshot finding yang sama.</p></div><button className="text-button" type="button" onClick={() => void load()}>Muat ulang state</button></div>
    {error && <p className="error-box" role="alert">{error}</p>}
    <div className="state-dimensions"><article><h3>Resolution otomatis</h3><StatusBadge status={resolutionView.label} /><p>{resolutionView.explanation}</p></article><article><h3>Review administratif</h3><StatusBadge status={reviewView.label} /><p>{reviewView.explanation}</p></article></div>
    <div className="review-form"><label htmlFor="review-note">Alasan atau catatan<textarea id="review-note" value={note} maxLength={1000} aria-describedby="review-note-help review-note-error" aria-invalid={note.length > 1000} onChange={event => setNote(event.target.value)} /></label><div className="note-meta"><span id="review-note-help">Alasan wajib untuk ManualReview/Ignore; teks biasa maksimum 1.000 karakter.</span><output aria-live="polite">{note.length}/1000</output></div>{note.length > 1000 && <p id="review-note-error" className="error-box">Catatan terlalu panjang.</p>}</div>
    {review.permissions.canRequestReview && <div className="action-group" aria-label="Permintaan review"><h3>Buat permintaan</h3>{(["ManualRemediation", "Ignore", "AcceptedRisk"] as FindingReviewRequestType[]).map(value => <button className="button secondary" type="button" disabled={busy} key={value} onClick={() => prepare({ kind: "request", value })}>{requestLabel(value)}</button>)}</div>}
    {review.permissions.canDecide && <div className="action-group" aria-label="Keputusan yang diizinkan server"><h3>Keputusan yang diizinkan server</h3>{review.allowedDecisions.map(value => <button className="button secondary" type="button" disabled={busy} key={value} onClick={() => prepare({ kind: "decision", value })}>{decisionLabel(value)}</button>)}</div>}
    {review.permissions.canReportManualRemediation && <button className="button" type="button" disabled={busy} onClick={() => prepare({ kind: "report" })}>Laporkan remediasi manual</button>}
    <section className="history" aria-labelledby="history-title"><h3 id="history-title">Riwayat review</h3>{review.events.length ? <ol>{review.events.map(event => <li key={event.sequence}><strong>{event.eventType}</strong><time dateTime={event.createdAt}>{new Date(event.createdAt).toLocaleString("id-ID")}</time>{event.note && <p className="review-note">{event.note}</p>}</li>)}</ol> : <p>Belum ada permintaan review.</p>}</section>
    <ConfirmationDialog open={Boolean(pending)} title={confirmationTitle(pending)} description={confirmationDescription(pending)} confirmLabel="Konfirmasi command" busy={busy} onConfirm={submit} onClose={() => { if (!busy) { setPending(undefined); key.current = undefined; } }} />
  </section>;
}
function requestLabel(value: FindingReviewRequestType) { return value === "ManualRemediation" ? "Remediasi manual" : value === "Ignore" ? "Minta Ignore" : "Minta Accepted Risk"; }
function decisionLabel(value: FindingReviewDecision) { return ({ ApproveManualRemediation: "Setujui remediasi manual", Ignore: "Putuskan Ignore", AcceptRisk: "Terima risiko", NeedsRevision: "Perlu revisi", Reject: "Tolak" } as const)[value]; }
function confirmationTitle(command?: Command) { return command?.kind === "report" ? "Laporkan remediasi manual?" : command?.kind === "request" ? "Kirim permintaan review?" : "Simpan keputusan review?"; }
function confirmationDescription(command?: Command) { const disposition = command && "value" in command ? String(command.value) : "laporan"; return `${disposition} akan ditambahkan sebagai event immutable. Ignore, Accepted Risk, dan laporan manual tidak berarti finding VerifiedResolved.`; }
function safeGovernanceError(value: unknown) { if (value instanceof ApiRequestError) return value.status === 401 ? "Sesi berakhir. Silakan masuk kembali." : value.status === 403 ? "Akses ditolak untuk workflow internal ini." : value.status === 404 ? "Finding tidak tersedia." : value.status === 409 ? "State berubah di tab lain. State canonical telah dimuat ulang; konfirmasi ulang command baru." : value.message; return "State tidak dapat diproses. Tidak ada detail internal yang ditampilkan."; }
