<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../services/Ppki.Api/Ppki.Api.csproj" />
    <ProjectReference Include="../../services/Ppki.Worker/Ppki.Worker.csproj" />
    <ProjectReference Include="../../src/Ppki.DocxEngine/Ppki.DocxEngine.csproj" />
    <ProjectReference Include="../../src/Ppki.Domain/Ppki.Domain.csproj" />
    <ProjectReference Include="../../src/Ppki.FixEngine/Ppki.FixEngine.csproj" />
    <ProjectReference Include="../../src/Ppki.Infrastructure/Ppki.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Ppki.RuleEngine/Ppki.RuleEngine.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../fixtures/docx/**" Link="fixtures/docx/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
