import { ApiContractError, fixEligibilityReasons, fixEligibilityStatuses, fixModes, type FixEligibilityReason, type FixEligibilityStatus, type FixMode } from "./audit-contract.ts";
import { fixExecutionStates, type FixExecutionState } from "./remediation-contract.ts";

export const fixPlanStates = ["Draft", "Approved", "Applying", "Completed", "Failed"] as const;
export const previewStates = ["Ready", "PartiallyAvailable", "Conflict", "Stale", "Unavailable"] as const;
export const previewItemStates = ["Previewable", "Ineligible", "Unavailable"] as const;
export const mutationItemStatuses = ["Independent", "Ordered", "DuplicateEquivalent", "Conflicting", "Stale", "Ineligible", "Unavailable", "DependencyCycle"] as const;
export const mutationRelationshipKinds = ["Independent", "RequiresBefore", "RequiresAfter", "DuplicateEquivalent", "Conflicting"] as const;

export type FixPlanState = (typeof fixPlanStates)[number];
export type PreviewState = (typeof previewStates)[number];
export type MutationItemStatus = (typeof mutationItemStatuses)[number];
type Rec = Record<string, unknown>;

export type FixPlanDraftItem = { id: string; findingId: string; ruleCode: string; validationKey: string; fixMode: FixMode; confidence: number | null; eligibility: FixEligibilityStatus; eligibilityReason: FixEligibilityReason; requiresExplicitApproval: boolean; createdAt: string };
export type FixPlanDraft = { id: string; state: FixPlanState; auditId: string; sourceDocumentVersionId: string; ownerUserId: string; createdAt: string; updatedAt: string; isStale: boolean; staleReasonCode: string | null; replayed: boolean; items: FixPlanDraftItem[] };
export type FixPlanLocation = { scope: string; bodyElementIndex: number | null; sectionIndex: number | null; paragraphIndex: number | null; runIndex: number | null };
export type FixPlanChange = { kind: string; propertyLabel: string; beforeLabel: string; beforeValue: string | null; afterLabel: string; afterValue: string | null; evidenceState: string };
export type MutationAnalysisItem = { itemId: string; findingId: string; status: MutationItemStatus; reasonCode: string; executionOrdinal: number | null; relatedItemIds: string[] };
export type MutationAnalysis = { schemaVersion: string; state: PreviewState; analyzableItemCount: number; independentItemCount: number; orderedItemCount: number; duplicateEquivalentItemCount: number; conflictItemCount: number; staleItemCount: number; items: MutationAnalysisItem[]; relationships: Array<{ itemId: string; relatedItemId: string; kind: (typeof mutationRelationshipKinds)[number]; beforeItemId: string | null; afterItemId: string | null; reasonCode: string }>; conflicts: Array<{ itemIds: string[]; reasonCode: string }>; reasonCodes: string[] };
export type FixPlanPreviewItem = { itemId: string; findingId: string; ruleCode: string; validationKey: string; fixMode: FixMode; confidence: number | null; eligibility: FixEligibilityStatus; eligibilityReason: FixEligibilityReason; requiresExplicitApproval: boolean; previewState: (typeof previewItemStates)[number]; reasonCode: string; propertyIdentifier: string | null; location: FixPlanLocation | null; change: FixPlanChange | null };
export type FixPlanPreview = { schemaVersion: string; planId: string; auditId: string; sourceDocumentVersionId: string; sourceVersionSha256: string; planState: FixPlanState; state: PreviewState; itemCount: number; previewableCount: number; ineligibleCount: number; unavailableCount: number; items: FixPlanPreviewItem[]; mutationAnalysis: MutationAnalysis | null };
export type FixPlanApproval = { planId: string; auditId: string; sourceDocumentVersionId: string; state: FixPlanState; snapshotSchemaVersion: string; planHash: string; sourceVersionSha256: string; approvedByUserId: string; approvedAt: string; itemCount: number; applyJobId: string; applyJobState: FixExecutionState; applyJobReplayed: boolean; replayed: boolean };

const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function rec(v: unknown): Rec { if (!v || typeof v !== "object" || Array.isArray(v)) throw new ApiContractError(); return v as Rec; }
function str(v: unknown): string { if (typeof v !== "string") throw new ApiContractError(); return v; }
function uuid(v: unknown): string { const x = str(v); if (!uuidPattern.test(x)) throw new ApiContractError(); return x; }
function bool(v: unknown): boolean { if (typeof v !== "boolean") throw new ApiContractError(); return v; }
function num(v: unknown): number { if (typeof v !== "number" || !Number.isFinite(v) || v < 0) throw new ApiContractError(); return v; }
function count(v: unknown): number { const x = num(v); if (!Number.isInteger(x)) throw new ApiContractError(); return x; }
function sha(v: unknown): string { const x = str(v); if (!/^[0-9a-f]{64}$/i.test(x)) throw new ApiContractError(); return x; }
function nullableNum(v: unknown): number | null { return v === null ? null : num(v); }
function nullableStr(v: unknown): string | null { return v === null ? null : str(v); }
function en<const T extends readonly string[]>(v: unknown, values: T): T[number] { if (typeof v !== "string" || !values.includes(v)) throw new ApiContractError(); return v as T[number]; }
function arr<T>(v: unknown, parse: (x: unknown) => T): T[] { if (!Array.isArray(v)) throw new ApiContractError(); return v.map(parse); }
function date(v: unknown): string { const x = str(v); if (!Number.isFinite(Date.parse(x))) throw new ApiContractError(); return x; }

function draftItem(v: unknown): FixPlanDraftItem { const x = rec(v); return { id: uuid(x.id), findingId: uuid(x.findingId), ruleCode: str(x.ruleCode), validationKey: str(x.validationKey), fixMode: en(x.fixMode, fixModes), confidence: nullableNum(x.confidence), eligibility: en(x.eligibility, fixEligibilityStatuses), eligibilityReason: en(x.eligibilityReason, fixEligibilityReasons), requiresExplicitApproval: bool(x.requiresExplicitApproval), createdAt: date(x.createdAt) }; }
export function parseFixPlanDraft(v: unknown): FixPlanDraft { const x = rec(v); return { id: uuid(x.id), state: en(x.state, fixPlanStates), auditId: uuid(x.auditId), sourceDocumentVersionId: uuid(x.sourceDocumentVersionId), ownerUserId: uuid(x.ownerUserId), createdAt: date(x.createdAt), updatedAt: date(x.updatedAt), isStale: bool(x.isStale), staleReasonCode: nullableStr(x.staleReasonCode), replayed: bool(x.replayed), items: arr(x.items, draftItem) }; }
function location(v: unknown): FixPlanLocation { const x = rec(v); return { scope: str(x.scope), bodyElementIndex: nullableNum(x.bodyElementIndex), sectionIndex: nullableNum(x.sectionIndex), paragraphIndex: nullableNum(x.paragraphIndex), runIndex: nullableNum(x.runIndex) }; }
function change(v: unknown): FixPlanChange { const x = rec(v); return { kind: str(x.kind), propertyLabel: str(x.propertyLabel), beforeLabel: str(x.beforeLabel), beforeValue: nullableStr(x.beforeValue), afterLabel: str(x.afterLabel), afterValue: nullableStr(x.afterValue), evidenceState: str(x.evidenceState) }; }
function analysisItem(v: unknown): MutationAnalysisItem { const x = rec(v); return { itemId: uuid(x.itemId), findingId: uuid(x.findingId), status: en(x.status, mutationItemStatuses), reasonCode: str(x.reasonCode), executionOrdinal: nullableNum(x.executionOrdinal), relatedItemIds: arr(x.relatedItemIds, uuid) }; }
function analysis(v: unknown): MutationAnalysis { const x = rec(v); return { schemaVersion: str(x.schemaVersion), state: en(x.state, previewStates), analyzableItemCount: num(x.analyzableItemCount), independentItemCount: num(x.independentItemCount), orderedItemCount: num(x.orderedItemCount), duplicateEquivalentItemCount: num(x.duplicateEquivalentItemCount), conflictItemCount: num(x.conflictItemCount), staleItemCount: num(x.staleItemCount), items: arr(x.items, analysisItem), relationships: arr(x.relationships, y => { const z = rec(y); return { itemId: uuid(z.itemId), relatedItemId: uuid(z.relatedItemId), kind: en(z.kind, mutationRelationshipKinds), beforeItemId: z.beforeItemId === null ? null : uuid(z.beforeItemId), afterItemId: z.afterItemId === null ? null : uuid(z.afterItemId), reasonCode: str(z.reasonCode) }; }), conflicts: arr(x.conflicts, y => { const z = rec(y); return { itemIds: arr(z.itemIds, uuid), reasonCode: str(z.reasonCode) }; }), reasonCodes: arr(x.reasonCodes, str) }; }
function previewItem(v: unknown): FixPlanPreviewItem { const x = rec(v); return { itemId: uuid(x.itemId), findingId: uuid(x.findingId), ruleCode: str(x.ruleCode), validationKey: str(x.validationKey), fixMode: en(x.fixMode, fixModes), confidence: nullableNum(x.confidence), eligibility: en(x.eligibility, fixEligibilityStatuses), eligibilityReason: en(x.eligibilityReason, fixEligibilityReasons), requiresExplicitApproval: bool(x.requiresExplicitApproval), previewState: en(x.previewState, previewItemStates), reasonCode: str(x.reasonCode), propertyIdentifier: nullableStr(x.propertyIdentifier), location: x.location === null ? null : location(x.location), change: x.change === null ? null : change(x.change) }; }
export function parseFixPlanPreview(v: unknown): FixPlanPreview { const x = rec(v); return { schemaVersion: str(x.schemaVersion), planId: uuid(x.planId), auditId: uuid(x.auditId), sourceDocumentVersionId: uuid(x.sourceDocumentVersionId), sourceVersionSha256: sha(x.sourceVersionSha256), planState: en(x.planState, fixPlanStates), state: en(x.state, previewStates), itemCount: count(x.itemCount), previewableCount: count(x.previewableCount), ineligibleCount: count(x.ineligibleCount), unavailableCount: count(x.unavailableCount), items: arr(x.items, previewItem), mutationAnalysis: x.mutationAnalysis === null ? null : analysis(x.mutationAnalysis) }; }
export function parseFixPlanApproval(v: unknown): FixPlanApproval { const x = rec(v); return { planId: uuid(x.planId), auditId: uuid(x.auditId), sourceDocumentVersionId: uuid(x.sourceDocumentVersionId), state: en(x.state, fixPlanStates), snapshotSchemaVersion: str(x.snapshotSchemaVersion), planHash: sha(x.planHash), sourceVersionSha256: sha(x.sourceVersionSha256), approvedByUserId: uuid(x.approvedByUserId), approvedAt: date(x.approvedAt), itemCount: count(x.itemCount), applyJobId: uuid(x.applyJobId), applyJobState: en(x.applyJobState, fixExecutionStates), applyJobReplayed: bool(x.applyJobReplayed), replayed: bool(x.replayed) }; }
