import assert from "node:assert/strict";
import test from "node:test";
import type { AuditFinding } from "./audit-contract.ts";
import type { FixPlanPreview } from "./fix-plan-contract.ts";
import { approvalBlockReason, canonicalFindingIds, isFixSelectable, maximumFixPlanItems, mergeFixSelection, selectionReason, toSelectedFinding } from "./fix-plan-selection.ts";

const finding = (fixMode: AuditFinding["fixMode"], eligibility: AuditFinding["eligibility"] = "Eligible", reason: AuditFinding["eligibilityReason"] = "Eligible") => ({ id: "10000000-0000-4000-8000-000000000001", domain: "Tata letak", ruleCode: "PPKI-1", fixMode, eligibility, eligibilityReason: reason }) as AuditFinding;
const preview = (): FixPlanPreview => ({ schemaVersion: "1", planId: "20000000-0000-4000-8000-000000000001", auditId: "30000000-0000-4000-8000-000000000001", sourceDocumentVersionId: "40000000-0000-4000-8000-000000000001", sourceVersionSha256: "a".repeat(64), planState: "Draft", state: "Ready", itemCount: 2, previewableCount: 2, ineligibleCount: 0, unavailableCount: 0, items: [{ itemId: "50000000-0000-4000-8000-000000000001", findingId: "10000000-0000-4000-8000-000000000001", ruleCode: "PPKI-1", validationKey: "page-size", fixMode: "Auto", confidence: 1, eligibility: "Eligible", eligibilityReason: "Eligible", requiresExplicitApproval: false, previewState: "Previewable", reasonCode: "preview-ready", propertyIdentifier: "width", location: null, change: null }, { itemId: "50000000-0000-4000-8000-000000000002", findingId: "10000000-0000-4000-8000-000000000002", ruleCode: "PPKI-2", validationKey: "margin", fixMode: "Confirm", confidence: 1, eligibility: "Eligible", eligibilityReason: "Eligible", requiresExplicitApproval: true, previewState: "Previewable", reasonCode: "preview-ready", propertyIdentifier: "margin", location: null, change: null }], mutationAnalysis: { schemaVersion: "1", state: "Ready", analyzableItemCount: 2, independentItemCount: 2, orderedItemCount: 0, duplicateEquivalentItemCount: 0, conflictItemCount: 0, staleItemCount: 0, items: [], relationships: [], conflicts: [], reasonCodes: [] } });

test("only backend-Eligible Auto and Confirm findings are selectable", () => { assert.equal(isFixSelectable(finding("Auto")), true); assert.equal(isFixSelectable(finding("Confirm")), true); assert.equal(isFixSelectable(finding("Manual")), false); assert.equal(isFixSelectable(finding("Report")), false); assert.equal(isFixSelectable(finding("Auto", "Ineligible", "AuditNotCompleted")), false); });
test("selection metadata preserves backend mode and domain", () => assert.deepEqual(toSelectedFinding(finding("Confirm")), { findingId: "10000000-0000-4000-8000-000000000001", domain: "Tata letak", ruleCode: "PPKI-1", fixMode: "Confirm" }));
test("canonical IDs are deduplicated and stable across page order", () => assert.deepEqual(canonicalFindingIds([{ findingId: "b", domain: "x", ruleCode: "2", fixMode: "Auto" }, { findingId: "a", domain: "x", ruleCode: "1", fixMode: "Auto" }, { findingId: "b", domain: "x", ruleCode: "2", fixMode: "Auto" }]), ["a", "b"]));
test("selection across pages remains deterministically bounded to the backend limit", () => { const values = Array.from({ length: maximumFixPlanItems + 5 }, (_, index) => ({ findingId: String(index), domain: "x", ruleCode: String(index), fixMode: "Auto" as const })); assert.equal(mergeFixSelection([], values).length, maximumFixPlanItems); });
test("Manual and Report remain visible with truthful non-selectable reasons", () => { assert.match(selectionReason(finding("Manual")), /manual/i); assert.match(selectionReason(finding("Report")), /tidak memiliki/i); });
test("Confirm selection is distinct from explicit item consent", () => assert.match(selectionReason(finding("Confirm")), /persetujuan eksplisit/i));
test("ready Auto plus Confirm plan blocks until exact Confirm item is checked", () => { const value = preview(); assert.match(approvalBlockReason(value, new Set())!, /1 item Confirm/); assert.equal(approvalBlockReason(value, new Set([value.items[1].itemId])), null); });
test("conflict stale and unavailable previews cannot be approved", () => { for (const state of ["Conflict", "Stale", "Unavailable"] as const) { const value = preview(); value.state = state; assert.ok(approvalBlockReason(value, new Set([value.items[1].itemId]))); } });
test("mutation conflicts remain approval blockers even if preview says Ready", () => { const value = preview(); value.mutationAnalysis!.conflictItemCount = 1; assert.ok(approvalBlockReason(value, new Set([value.items[1].itemId]))); });
test("dependency cycles remain blockers even if aggregate counts are malformedly optimistic", () => { const value = preview(); value.mutationAnalysis!.items = [{ itemId: value.items[0].itemId, findingId: value.items[0].findingId, status: "DependencyCycle", reasonCode: "dependency-cycle", executionOrdinal: null, relatedItemIds: [] }]; assert.ok(approvalBlockReason(value, new Set([value.items[1].itemId]))); });
