import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const api = readFileSync(new URL("./fix-plan-api.ts", import.meta.url), "utf8");
const workflow = readFileSync(new URL("../components/fix-plan-workflow.tsx", import.meta.url), "utf8");
const list = readFileSync(new URL("../components/audit-finding-list.tsx", import.meta.url), "utf8");
const model = readFileSync(new URL("./fix-plan-selection.ts", import.meta.url), "utf8");
const contract = readFileSync(new URL("./fix-plan-contract.ts", import.meta.url), "utf8");
const sharedApi = readFileSync(new URL("./api.ts", import.meta.url), "utf8");
const styles = readFileSync(new URL("../app/globals.css", import.meta.url), "utf8");

test("workflow persists the selected draft before loading its GET preview", () => { const create = workflow.indexOf("createFixPlanDraft"); const preview = workflow.indexOf("previewFixPlanDraft", create); assert.ok(create >= 0 && preview > create); assert.match(api, /method: "PUT"/); });
test("create carries an idempotency key and updates reuse the existing plan", () => { assert.match(api, /"Idempotency-Key": idempotencyKey/); assert.match(workflow, /draft\?\.state === "Draft"[\s\S]*updateFixPlanDraft/); });
test("approval uses only the S7 approval endpoint and never calls execution", () => { assert.match(api, /\/approval/); assert.doesNotMatch(api + workflow, /fix-executions|executeFix|reaudit|setInterval/); });
test("approval sends explicit Confirm item IDs and prevents duplicate clicks", () => { assert.match(workflow, /\[\.\.\.approvedIds\]\.sort\(\)/); assert.match(workflow, /if \(!preview \|\| approvalBlockReason\(preview, approvedIds\) \|\| busy\) return/); });
test("selection is page-local for Fix All but stored above the paginated view", () => { assert.match(list, /useState<SelectedFixFinding\[\]>/); assert.match(list, /page\.items\.map\(toSelectedFinding\)/); assert.match(list, /halaman ini/); });
test("Manual Report and ineligible findings never receive a selection checkbox", () => assert.match(list, /isFixSelectable\(item\) && <input/));
test("in-flight requests abort and stale identity responses are rejected", () => { assert.match(workflow, /controller\?\.abort/); assert.match(workflow, /sequence !== request\.current\.sequence/); assert.match(workflow, /sourceDocumentVersionId !== identity\.documentVersionId/); });
test("the UI reports queue state without polling or claiming completion", () => { assert.match(workflow, /applyJobState/); assert.match(workflow, /belum berarti dokumen sudah diperbaiki/); });
test("native controls and labelled review regions preserve keyboard accessibility", () => { assert.match(workflow, /type="checkbox"/); assert.match(workflow, /aria-labelledby="fix-plan-review-title"/); assert.match(list, /aria-label={`Pilih/); });
test("checkbox selection cannot call approval or apply", () => { assert.doesNotMatch(list, /approveFixPlan|fix-executions/); });
test("Fix All Safe only merges authoritative items on the loaded page", () => { assert.match(list, /page\.items\.map\(toSelectedFinding\)/); assert.doesNotMatch(list, /pageSize:\s*100000|fetchAll/); });
test("opening review creates or updates a draft rather than applying", () => { assert.match(workflow, /async function review/); assert.doesNotMatch(workflow.slice(workflow.indexOf("async function review"), workflow.indexOf("async function approve")), /approveFixPlan|fix-executions/); });
test("preview loading is a read-only GET", () => { assert.match(api, /previewFixPlanDraft[\s\S]*\/preview`, \{ signal \}/); });
test("toggling Confirm consent has no network side effect", () => { const consent = workflow.slice(workflow.indexOf("confirm-consent")); assert.doesNotMatch(consent.slice(0, consent.indexOf("</article>")), /approveFixPlan|apiFetch/); });
test("draft create binds canonical audit and canonical selected IDs", () => { assert.match(workflow, /createFixPlanDraft\(identity\.auditId, ids/); assert.match(workflow, /sourceDocumentVersionId !== identity\.documentVersionId/); });
test("draft update preserves the authoritative draft plan ID", () => assert.match(workflow, /updateFixPlanDraft\(identity\.auditId, draft\.id, ids/));
test("uncertain create retries keep one idempotency key per selection intent", () => { assert.match(workflow, /createIntent\.current\.signature !== signature/); assert.match(workflow, /createIntent\.current\.key/); });
test("duplicate selected IDs are removed before submission", () => assert.match(model, /new Set\(values\.map/));
test("finding filters search pagination and ordering remain server-owned", () => { assert.match(list, /listAuditFindings\(identity\.auditId, filters/); assert.match(list, /findingsQuery\(next\)/); });
test("review groups preview items by domain and safe location", () => { assert.match(workflow, /meta\?\.domain/); assert.match(workflow, /locationLabel\(item\)/); });
test("safe backend before and after labels and values are rendered", () => { assert.match(workflow, /change\.beforeLabel/); assert.match(workflow, /change\.afterLabel/); });
test("frontend contract consumes preview fields instead of actual expected JSON", () => { assert.doesNotMatch(workflow, /actualJson|expectedJson|rules\.json/); assert.match(contract, /FixPlanDraftBeforeAfterDto|FixPlanChange/); });
test("conflict summaries are exposed before approval", () => { assert.match(workflow, /Konflik terdeteksi/); assert.match(workflow, /mutationAnalysis\.conflicts/); });
test("duplicate-equivalent analysis is preserved as typed server truth", () => { assert.match(contract, /DuplicateEquivalent/); assert.match(workflow, /status\?\.status/); });
test("safe independent items share one persisted review plan", () => { assert.match(contract, /Independent/); assert.match(workflow, /value\.items/); });
test("stale preview state withholds approval", () => assert.match(model, /preview\.state !== "Ready"/));
test("409 forces authoritative finding refresh and a new review", () => { assert.match(workflow, /value\.status === 409[\s\S]*onAuthoritativeRefresh/); assert.match(list, /onAuthoritativeRefresh=.*setReload/); });
test("source-version changes abort and invalidate active review state", () => { assert.match(workflow, /identity\.documentVersionId/); assert.match(workflow, /setPreview\(undefined\)/); });
test("late preview cannot install itself over a newer request", () => assert.match(workflow, /sequence !== request\.current\.sequence \|\| value\.planId !== persisted\.id/));
test("late draft cannot install itself over a newer selection", () => assert.match(workflow, /sequence !== request\.current\.sequence \|\| signature !==/));
test("approval request body contains consent IDs only", () => { assert.match(api, /JSON\.stringify\(\{ approvedConfirmItemIds \}\)/); assert.doesNotMatch(api.slice(api.indexOf("approveFixPlan")), /preview|conflict|beforeValue/); });
test("successful approval displays returned immutable plan state", () => { assert.match(workflow, /setApproval\(value\)/); assert.match(workflow, /Rencana telah disetujui/); });
test("approved plans lock draft editing", () => { assert.match(workflow, /onApproved\(\)/); assert.match(list, /setFixSelectionLocked\(true\)/); });
test("401 delegates to the established shared redirect", () => { assert.match(api, /apiFetch/); assert.match(sharedApi, /response\.status === 401/); assert.match(sharedApi, /redirectToLogin/); });
test("403 and 404 use non-disclosing copy", () => { assert.match(model, /error\.status === 403 \|\| error\.status === 404/); assert.doesNotMatch(model, /problem\.detail|problem\.title/); });
test("409 copy explicitly requires preview refresh", () => assert.match(model, /Perbarui preview/));
test("AbortError is silent in review and approval", () => { assert.equal((workflow.match(/!isApiRequestAborted\(value\)/g) ?? []).length, 2); });
test("raw ProblemDetails fields never enter the fix-plan presentation", () => assert.doesNotMatch(workflow + model, /\.problem\.(detail|title|extensions)/));
test("Auto and Confirm distinction is textual rather than color-only", () => { assert.match(workflow, /item\.fixMode/); assert.match(model, /item Confirm/); });
test("primary selection consent and approval controls are native keyboard controls", () => { assert.match(list, /type="checkbox"/); assert.match(workflow, /type="checkbox"/); assert.match(workflow, /type="button"/); });
test("responsive CSS stacks approval-critical content at narrow width", () => { assert.match(styles, /max-width:620px/); assert.match(styles, /fix-plan-change\{grid-template-columns:1fr/); assert.match(styles, /fix-plan-toolbar\{align-items:stretch;flex-direction:column/); });
test("S7-T07 adds no execution polling or Sprint 8 integration", () => assert.doesNotMatch(api + workflow + list, /setTimeout|setInterval|fix-executions|reaudit/));
