import { ApiRequestError } from "./api.ts";
import type { AuditFinding } from "./audit-contract.ts";
import type { FixPlanPreview } from "./fix-plan-contract.ts";

export type SelectedFixFinding = { findingId: string; domain: string; ruleCode: string; fixMode: "Auto" | "Confirm" };
export const maximumFixPlanItems = 100;
export function isFixSelectable(finding: AuditFinding): boolean { return finding.eligibility === "Eligible" && (finding.fixMode === "Auto" || finding.fixMode === "Confirm"); }
export function toSelectedFinding(finding: AuditFinding): SelectedFixFinding | null { return isFixSelectable(finding) ? { findingId: finding.id, domain: finding.domain, ruleCode: finding.ruleCode, fixMode: finding.fixMode as "Auto" | "Confirm" } : null; }
export function canonicalFindingIds(values: SelectedFixFinding[]): string[] { return [...new Set(values.map(x => x.findingId))].sort(); }
export function mergeFixSelection(current: SelectedFixFinding[], additions: SelectedFixFinding[]): SelectedFixFinding[] { const values = new Map(current.map(value => [value.findingId, value])); for (const value of additions) if (values.size < maximumFixPlanItems || values.has(value.findingId)) values.set(value.findingId, value); return [...values.values()]; }
export function selectionReason(finding: AuditFinding): string { if (finding.fixMode === "Manual") return "Perbaikan manual; tidak dapat dipilih."; if (finding.fixMode === "Report") return "Temuan laporan; tidak memiliki perubahan otomatis."; if (finding.eligibility !== "Eligible") return `Tidak dapat dipilih (${finding.eligibilityReason}).`; return finding.fixMode === "Confirm" ? "Memerlukan persetujuan eksplisit saat review." : "Dapat diperbaiki otomatis setelah rencana disetujui."; }
export function approvalBlockReason(preview: FixPlanPreview, approved: ReadonlySet<string>): string | null { if (preview.state !== "Ready" || preview.planState !== "Draft") return "Rencana belum siap disetujui. Perbarui preview."; if (!preview.mutationAnalysis || preview.mutationAnalysis.state !== "Ready" || preview.mutationAnalysis.conflictItemCount || preview.mutationAnalysis.staleItemCount || preview.mutationAnalysis.items.some(x => ["Conflicting", "Stale", "Ineligible", "Unavailable", "DependencyCycle"].includes(x.status))) return "Konflik atau dependensi belum aman untuk disetujui."; if (preview.items.some(x => x.previewState !== "Previewable" || x.eligibility !== "Eligible")) return "Ada item yang tidak tersedia atau tidak lagi memenuhi syarat."; const missing = preview.items.filter(x => x.requiresExplicitApproval && !approved.has(x.itemId)); return missing.length ? `${missing.length} item Confirm belum disetujui secara eksplisit.` : null; }
export function fixPlanError(error: unknown): string { if (error instanceof ApiRequestError) { if (error.status === 409) return "Rencana berubah atau kedaluwarsa. Perbarui preview sebelum melanjutkan."; if (error.status === 403 || error.status === 404) return "Rencana tidak tersedia atau tidak dapat diakses."; return error.message; } return "Rencana perbaikan tidak dapat diproses. Coba lagi."; }
export function newIdempotencyKey(): string { return crypto.randomUUID(); }
