import assert from "node:assert/strict";
import test from "node:test";
import { ApiContractError } from "./audit-contract.ts";
import { parseFixPlanApproval, parseFixPlanDraft, parseFixPlanPreview } from "./fix-plan-contract.ts";

const ids = { plan: "10000000-0000-4000-8000-000000000001", audit: "20000000-0000-4000-8000-000000000001", version: "30000000-0000-4000-8000-000000000001", owner: "40000000-0000-4000-8000-000000000001", item: "50000000-0000-4000-8000-000000000001", finding: "60000000-0000-4000-8000-000000000001", job: "70000000-0000-4000-8000-000000000001" };
const now = "2026-08-25T08:00:00+00:00";
const draft = { id: ids.plan, state: "Draft", auditId: ids.audit, sourceDocumentVersionId: ids.version, ownerUserId: ids.owner, createdAt: now, updatedAt: now, isStale: false, staleReasonCode: null, replayed: false, items: [{ id: ids.item, findingId: ids.finding, ruleCode: "PPKI-1", validationKey: "page-size", fixMode: "Confirm", confidence: 1, eligibility: "Eligible", eligibilityReason: "Eligible", requiresExplicitApproval: true, createdAt: now }] };
const analysis = { schemaVersion: "1", state: "Ready", analyzableItemCount: 1, independentItemCount: 1, orderedItemCount: 0, duplicateEquivalentItemCount: 0, conflictItemCount: 0, staleItemCount: 0, items: [{ itemId: ids.item, findingId: ids.finding, status: "Independent", reasonCode: "independent", mutationKey: null, executionOrdinal: 0, relatedItemIds: [] }], relationships: [], conflicts: [], reasonCodes: [] };
const preview = { schemaVersion: "1", planId: ids.plan, auditId: ids.audit, sourceDocumentVersionId: ids.version, sourceVersionSha256: "a".repeat(64), planState: "Draft", state: "Ready", itemCount: 1, previewableCount: 1, ineligibleCount: 0, unavailableCount: 0, items: [{ itemId: ids.item, findingId: ids.finding, ruleCode: "PPKI-1", validationKey: "page-size", fixMode: "Confirm", confidence: 1, eligibility: "Eligible", eligibilityReason: "Eligible", requiresExplicitApproval: true, previewState: "Previewable", reasonCode: "preview-ready", capabilityId: "page-size", capabilityVersion: "1", propertyIdentifier: "page.width", location: { scope: "Document", bodyElementIndex: null, sectionIndex: 0, paragraphIndex: null, runIndex: null }, change: { kind: "measurement", propertyLabel: "Lebar", beforeLabel: "Sebelum", beforeValue: "200 mm", afterLabel: "Sesudah", afterValue: "210 mm", evidenceState: "Complete" } }], mutationAnalysis: analysis };

test("draft parser preserves authoritative eligibility and Confirm consent requirement", () => { const value = parseFixPlanDraft(draft); assert.equal(value.items[0].eligibility, "Eligible"); assert.equal(value.items[0].requiresExplicitApproval, true); });
test("preview parser preserves safe before-after location and mutation analysis", () => { const value = parseFixPlanPreview(preview); assert.equal(value.items[0].change?.afterValue, "210 mm"); assert.equal(value.items[0].location?.sectionIndex, 0); assert.equal(value.mutationAnalysis?.items[0].status, "Independent"); });
test("approval parser accepts authoritative immutable snapshot and queued apply job", () => { const value = parseFixPlanApproval({ planId: ids.plan, auditId: ids.audit, sourceDocumentVersionId: ids.version, state: "Approved", snapshotSchemaVersion: "1", planHash: "b".repeat(64), sourceVersionSha256: "a".repeat(64), approvedByUserId: ids.owner, approvedAt: now, itemCount: 1, applyJobId: ids.job, applyJobState: "Queued", applyJobReplayed: false, replayed: false }); assert.equal(value.state, "Approved"); assert.equal(value.applyJobState, "Queued"); });
test("contracts reject unknown lifecycle mutation and execution states", () => { assert.throws(() => parseFixPlanDraft({ ...draft, state: "Ready" }), ApiContractError); assert.throws(() => parseFixPlanPreview({ ...preview, mutationAnalysis: { ...analysis, state: "Resolved" } }), ApiContractError); assert.throws(() => parseFixPlanApproval({ planId: ids.plan, auditId: ids.audit, sourceDocumentVersionId: ids.version, state: "Approved", snapshotSchemaVersion: "1", planHash: "b".repeat(64), sourceVersionSha256: "a".repeat(64), approvedByUserId: ids.owner, approvedAt: now, itemCount: 1, applyJobId: ids.job, applyJobState: "Done", applyJobReplayed: false, replayed: false }), ApiContractError); });
test("contracts reject malformed hashes counts and identities", () => { assert.throws(() => parseFixPlanPreview({ ...preview, sourceVersionSha256: "secret" }), ApiContractError); assert.throws(() => parseFixPlanPreview({ ...preview, itemCount: 1.5 }), ApiContractError); assert.throws(() => parseFixPlanDraft({ ...draft, auditId: "not-an-id" }), ApiContractError); });
