import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),"utf8");
const workflow=read("../components/remediation-workflow.tsx"),governance=read("../components/finding-governance-panel.tsx"),dialog=read("../components/confirmation-dialog.tsx"),api=read("./remediation-api.ts"),baseApi=read("./api.ts"),detail=read("../components/finding-detail-client.tsx"),list=read("../components/audit-findings-client.tsx"),css=read("../app/globals.css"),signup=read("../app/signup/page.tsx"),presentation=read("./findings-presentation.ts"),badge=read("../components/status-badge.tsx");
const combined=[workflow,governance,dialog,api,detail,list].join("\n");
const checks:[string,()=>void][]=[
["preview sends only finding IDs",()=>{assert.match(api,/JSON\.stringify\(\{ findingIds \}\)/);assert.doesNotMatch(api,/body: JSON\.stringify\(\{[^}]*operation/i)}],
["apply sends exact IDs and hash",()=>assert.match(api,/JSON\.stringify\(\{ findingIds, planHash \}\)/)],
["idempotency uses request header",()=>assert.match(api,/"Idempotency-Key": idempotencyKey/)],
["lost-response keeps intent key",()=>assert.match(workflow,/intentKey\.current/)],
["selection invalidates preview",()=>assert.match(workflow,/setPreview\(undefined\)/)],
["apply requires dialog",()=>assert.match(workflow,/ConfirmationDialog[\s\S]*Terapkan exact plan/)],
["no optimistic Completed",()=>assert.doesNotMatch(workflow,/state:\s*["']Completed/)],
["poll is sequential timeout",()=>{assert.match(workflow,/setTimeout\(poll/);assert.doesNotMatch(workflow,/setInterval/)}],
["poll aborts on unmount",()=>assert.match(workflow,/active\?\.abort\(\)/)],
["visible tab refreshes",()=>assert.match(workflow,/visibilitychange/)],
["terminal state stops poll",()=>assert.match(workflow,/isTerminalExecution/)],
["retryPending warns against apply",()=>assert.match(workflow,/Jangan menjalankan apply lagi/)],
["no manual retry action",()=>assert.doesNotMatch(combined,/manual retry|retry manual/i)],
["re-audit action is server-state gated",()=>assert.match(workflow,/canCreateReaudit/)],
["comparison is server fetched",()=>assert.match(api,/\/comparison\?page=1&pageSize=100/)],
["no frontend finding matcher",()=>assert.doesNotMatch(workflow,/fingerprint|levenshtein|fuzzy/i)],
["reconciliation POST is bodyless",()=>assert.match(api,/resolution-reconciliation[^}]+method: "POST"/)],
["state dimensions are separate",()=>assert.match(governance,/Resolution otomatis[\s\S]*Review administratif/)],
["non-verified review warning is explicit",()=>assert.match(governance,/Ignore, Accepted Risk/)],
["decisions come from server",()=>assert.match(governance,/review\.allowedDecisions\.map/)],
["self-review has no actor predicate",()=>assert.doesNotMatch(governance,/actorUserId\s*[!=]=|requestedByUserId\s*[!=]=/)],
["note max is 1000",()=>assert.match(governance,/maxLength=\{1000\}/)],
["note counter is accessible",()=>assert.match(governance,/<output aria-live="polite">/)],
["note is React text",()=>assert.match(governance,/\{event\.note\}/)],
["no HTML injection",()=>assert.doesNotMatch(combined,/dangerouslySetInnerHTML/)],
["no browser persistence",()=>assert.doesNotMatch(combined,/localStorage|sessionStorage|indexedDB/)],
["no production console logging",()=>assert.doesNotMatch(combined,/console\./)],
["no token role authorization",()=>assert.doesNotMatch(combined,/user_metadata|app_metadata|token.*role|role.*token/i)],
["no actor ID in request",()=>assert.doesNotMatch(api,/actorUserId|adminId|ownerUserId/)],
["401 follows login convention",()=>assert.match(baseApi,/status === 401[\s\S]*\/login\?next=/)],
["403 is safely presented",()=>assert.match(workflow,/Akses ditolak/)],
["404 is non-enumerating",()=>assert.match(workflow,/Resource tidak tersedia/)],
["409 invalidates preview",()=>assert.match(workflow,/value\.status === 409[\s\S]*setPreview\(undefined\)/)],
["raw ProblemDetails is absent",()=>assert.doesNotMatch(combined,/problem\.detail|response\.detail|exception\.message/)],
["signup remains disabled",()=>{assert.match(signup,/Pendaftaran ditutup/);assert.doesNotMatch(signup,/signUp\(/)}],
["selection is honestly labeled as candidate",()=>assert.match(workflow,/Selection ini hanya kandidat/)],
["server preview makes final eligibility decision",()=>{assert.match(workflow,/preview\.items\.filter\(item => item\.disposition !== "Planned"\)/);assert.match(workflow,/Kandidat yang tidak eligible/)}],
["eligibility never uses FixMode",()=>assert.doesNotMatch(workflow,/fixMode/)],
["list does not preview per row or page",()=>assert.doesNotMatch(list,/previewFixPlan/)],
["preview is requested only for exact selection",()=>assert.match(workflow,/previewFixPlan\(auditId, selected(?:, controller\.signal)?\)/)],
["commands have synchronous duplicate guards",()=>{assert.match(workflow,/commandInFlight\.current/);assert.match(governance,/commandInFlight\.current/)}],
["audit change clears workflow state",()=>assert.match(workflow,/setExecution\(undefined\)[\s\S]*setComparison\(undefined\)[\s\S]*\[auditId\]/)],
["selection change aborts stale preview",()=>assert.match(workflow,/previewRequest\.current\?\.abort\(\)/)],
["audit change ignores stale command response",()=>assert.match(workflow,/activeAuditId\.current !== commandAuditId/)],
["audit change resets selection",()=>assert.match(list,/setSelectedFindingIds\(\[\]\).*\[auditId\]/)],
["large list remains paginated",()=>assert.match(list,/page\.items\.map/)],
["governance is lazy on detail",()=>assert.match(detail,/FindingGovernancePanel/)],
["no synthetic page or line",()=>assert.doesNotMatch(workflow,/pageIndex|lineIndex/)],
["location fallback is explicit",()=>assert.match(presentation,/Lokasi rinci tidak tersedia/)],
["dialog title and description are linked",()=>assert.match(dialog,/aria-labelledby="confirm-title" aria-describedby="confirm-description"/)],
["dialog supports Escape",()=>assert.match(dialog,/onCancel=/)],
["dialog restores focus",()=>assert.match(dialog,/trigger\.current\?\.focus/)],
["visible button focus exists",()=>assert.match(css,/button:focus-visible/)],
["badges contain text",()=>assert.match(badge,/>\{status\}</)],
["tablet breakpoint exists",()=>assert.match(css,/max-width:900px/)],
["mobile breakpoint exists",()=>assert.match(css,/max-width:700px/)],
["storage API is absent",()=>assert.doesNotMatch(api,/storage\/v1|bucket|filename/i)],
["document payload persistence is absent",()=>assert.doesNotMatch(combined,/document\.xml|approvedPlan/i)],
["review is not loaded per row",()=>assert.doesNotMatch(list,/getFindingReview/)],
["actual endpoint set is centralized",()=>assert.match(api,/fix-plan-preview[\s\S]*fix-executions[\s\S]*re-audit[\s\S]*comparison[\s\S]*resolution[\s\S]*review/)],
];
for(const [name,run] of checks)test(name,run);
