import { apiFetch } from "./api";
import { parseAuditSummary, type AuditSummary } from "./audit-contract";
import { parseAuditComparison, parseFindingResolution, parseFindingReview, parseFindingReviewCommand, parseFixExecutionAccepted, parseFixExecutionStatus, parseFixPlanPreview, parseReauditAccepted, type AuditComparison, type FindingResolution, type FindingReview, type FindingReviewDecision, type FindingReviewRequestType, type FixExecutionAccepted, type FixExecutionStatus, type FixPlanPreview, type ReauditAccepted } from "./remediation-contract";

export async function previewFixPlan(auditId: string, findingIds: string[], signal?: AbortSignal): Promise<FixPlanPreview> { return parseFixPlanPreview(await apiFetch(`/api/audits/${encodeURIComponent(auditId)}/fix-plan-preview`, { method: "POST", body: JSON.stringify({ findingIds }), signal })); }
export async function createFixExecution(auditId: string, findingIds: string[], planHash: string, idempotencyKey: string): Promise<FixExecutionAccepted> { return parseFixExecutionAccepted(await apiFetch(`/api/audits/${encodeURIComponent(auditId)}/fix-executions`, { method: "POST", headers: { "Idempotency-Key": idempotencyKey }, body: JSON.stringify({ findingIds, planHash }) })); }
export async function getFixExecution(auditId: string, executionId: string, signal?: AbortSignal): Promise<FixExecutionStatus> { return parseFixExecutionStatus(await apiFetch(`/api/audits/${encodeURIComponent(auditId)}/fix-executions/${encodeURIComponent(executionId)}`, { signal })); }
export async function createReaudit(executionId: string): Promise<ReauditAccepted> { return parseReauditAccepted(await apiFetch(`/api/fix-executions/${encodeURIComponent(executionId)}/re-audit`, { method: "POST" })); }
export async function getReaudit(auditId: string, signal?: AbortSignal): Promise<AuditSummary> { return parseAuditSummary(await apiFetch(`/api/audits/${encodeURIComponent(auditId)}`, { signal })); }
export async function getComparison(executionId: string, signal?: AbortSignal): Promise<AuditComparison> { return parseAuditComparison(await apiFetch(`/api/fix-executions/${encodeURIComponent(executionId)}/comparison?page=1&pageSize=100`, { signal })); }
export async function reconcileResolution(executionId: string): Promise<void> { await apiFetch(`/api/fix-executions/${encodeURIComponent(executionId)}/resolution-reconciliation`, { method: "POST" }); }
export async function getFindingResolution(auditId: string, findingId: string, signal?: AbortSignal): Promise<FindingResolution> { return parseFindingResolution(await apiFetch(`/api/audits/${encodeURIComponent(auditId)}/findings/${encodeURIComponent(findingId)}/resolution`, { signal })); }
export async function getFindingReview(auditId: string, findingId: string, signal?: AbortSignal): Promise<FindingReview> { return parseFindingReview(await apiFetch(`/api/audits/${encodeURIComponent(auditId)}/findings/${encodeURIComponent(findingId)}/review`, { signal })); }
export async function requestFindingReview(auditId: string, findingId: string, requestedDisposition: FindingReviewRequestType, note: string, key: string, signal?: AbortSignal): Promise<FindingReview> { return parseFindingReviewCommand(await apiFetch(`/api/audits/${encodeURIComponent(auditId)}/findings/${encodeURIComponent(findingId)}/review-requests`, { method: "POST", headers: { "Idempotency-Key": key }, body: JSON.stringify({ requestedDisposition, note: note.trim() || null }), signal })); }
export async function decideFindingReview(caseId: string, decision: FindingReviewDecision, note: string, key: string, signal?: AbortSignal): Promise<FindingReview> { return parseFindingReviewCommand(await apiFetch(`/api/finding-reviews/${encodeURIComponent(caseId)}/decisions`, { method: "POST", headers: { "Idempotency-Key": key }, body: JSON.stringify({ decision, note: note.trim() || null }), signal })); }
export async function reportManualRemediation(caseId: string, note: string, key: string): Promise<FindingReview> { return parseFindingReviewCommand(await apiFetch(`/api/finding-reviews/${encodeURIComponent(caseId)}/manual-remediation-reports`, { method: "POST", headers: { "Idempotency-Key": key }, body: JSON.stringify({ note: note.trim() || null }) })); }
